services:
  db:
    image: anittababu/crud-api-db
    environment:
      POSTGRES_DB: patient
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
    ports:
      - "5436:5432"

  app:
    image: anittababu/crud-api-app
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: anittababu/crud-api-redis
    ports:
      - "6379:6379"
