services:
  db:
    image: anittababu/patient-crudapi-db
    environment:
      POSTGRES_DB: patient
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password1234
    ports:
      - "5436:5432"

  app:
    image: anittababu/patient-crudapi-app
    build: .
    ports:
      - "5000:5000"
